package orm;
// Generated 21-ene-2025 8:52:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Libro generated by hbm2java
 */
@Entity
@Table(name="libro"
    ,catalog="ut3demo1"
)
public class Libro  implements java.io.Serializable {


     private int isbn;
     private String titulo;
     private String autor;

    public Libro() {
    }

	
    public Libro(int isbn) {
        this.isbn = isbn;
    }
    public Libro(int isbn, String titulo, String autor) {
       this.isbn = isbn;
       this.titulo = titulo;
       this.autor = autor;
    }
   
    
    @Id 
    @Column(name="isbn", unique=true, nullable=false)
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }

    
    @Column(name="titulo", length=100)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="autor", length=100)
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }

    @Override
    public String toString() {
        return "Libro{" + "isbn=" + isbn + ", titulo=" + titulo + ", autor=" + autor + '}';
    }
}


