/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package examenizanperez;

import examenizanperez.logica.Coche;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author IzanPerezDímas
 */
public class NuevoCoche extends javax.swing.JDialog {

    /**
     * Creates new form NuevoCoche
     */
    public NuevoCoche(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Llamo al evento del slider de color para que se estableza el color de los componentes
        jSliderColorStateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTransmision = new javax.swing.ButtonGroup();
        buttonGroupCombustible = new javax.swing.ButtonGroup();
        jLabelMarca = new javax.swing.JLabel();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jLabelFechaMatriculacion = new javax.swing.JLabel();
        jSpinnerFechaMatriculacion = new javax.swing.JSpinner();
        jLabelKilometros = new javax.swing.JLabel();
        jSliderKilometros = new javax.swing.JSlider();
        jSliderColor = new javax.swing.JSlider();
        jLabelColor = new javax.swing.JLabel();
        jLabelTransmision = new javax.swing.JLabel();
        jRadioButtonManual = new javax.swing.JRadioButton();
        jRadioButtonAutomatica = new javax.swing.JRadioButton();
        jSeparator = new javax.swing.JSeparator();
        jLabelCombustible = new javax.swing.JLabel();
        jRadioButtonGasolina = new javax.swing.JRadioButton();
        jRadioButtonDiesel = new javax.swing.JRadioButton();
        jRadioButtonHibrido = new javax.swing.JRadioButton();
        jRadioButtonElectrico = new javax.swing.JRadioButton();
        jButtonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang"); // NOI18N
        jLabelMarca.setText(bundle.getString("marca")); // NOI18N

        jComboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {App.bundle.getString("seleccionaMarca"), "Renault", "Citroen", "Ford", "Audi", "Peugeot", "Seat", "Opel" }));

        jLabelFechaMatriculacion.setText(bundle.getString("matriculacion")); // NOI18N

        jSpinnerFechaMatriculacion.setModel(new javax.swing.SpinnerNumberModel(2023, 1900, 2023, 1));

        jLabelKilometros.setText(bundle.getString("kilometros")); // NOI18N

        jSliderKilometros.setMajorTickSpacing(50);
        jSliderKilometros.setMaximum(300);
        jSliderKilometros.setPaintLabels(true);
        jSliderKilometros.setPaintTicks(true);
        jSliderKilometros.setSnapToTicks(true);

        jSliderColor.setMajorTickSpacing(50);
        jSliderColor.setMaximum(250);
        jSliderColor.setPaintLabels(true);
        jSliderColor.setPaintTicks(true);
        jSliderColor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderColorStateChanged(evt);
            }
        });

        jLabelColor.setText(bundle.getString("color")); // NOI18N

        jLabelTransmision.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTransmision.setText(bundle.getString("tipoTransmision")); // NOI18N

        buttonGroupTransmision.add(jRadioButtonManual);
        jRadioButtonManual.setText(bundle.getString("manual")); // NOI18N
        jRadioButtonManual.setActionCommand(bundle.getString("manual")); // NOI18N
        jRadioButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonManualActionPerformed(evt);
            }
        });

        buttonGroupTransmision.add(jRadioButtonAutomatica);
        jRadioButtonAutomatica.setText(bundle.getString("automatica")); // NOI18N
        jRadioButtonAutomatica.setActionCommand(bundle.getString("automatica")); // NOI18N

        jSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelCombustible.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCombustible.setText(bundle.getString("tipoCombustible")); // NOI18N

        buttonGroupCombustible.add(jRadioButtonGasolina);
        jRadioButtonGasolina.setText(bundle.getString("gasolina")); // NOI18N
        jRadioButtonGasolina.setActionCommand(bundle.getString("gasolina")); // NOI18N

        buttonGroupCombustible.add(jRadioButtonDiesel);
        jRadioButtonDiesel.setText(bundle.getString("diesel")); // NOI18N
        jRadioButtonDiesel.setActionCommand(bundle.getString("diesel")); // NOI18N

        buttonGroupCombustible.add(jRadioButtonHibrido);
        jRadioButtonHibrido.setText(bundle.getString("hibrido")); // NOI18N
        jRadioButtonHibrido.setActionCommand(bundle.getString("hibrido")); // NOI18N

        buttonGroupCombustible.add(jRadioButtonElectrico);
        jRadioButtonElectrico.setText(bundle.getString("electrico")); // NOI18N
        jRadioButtonElectrico.setActionCommand(bundle.getString("electrico")); // NOI18N

        jButtonGuardar.setText(bundle.getString("guardar")); // NOI18N
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTransmision)
                                .addGap(51, 51, 51)
                                .addComponent(jLabelCombustible))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelMarca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelFechaMatriculacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinnerFechaMatriculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelKilometros)
                                        .addComponent(jLabelColor))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSliderColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSliderKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAutomatica)
                            .addComponent(jRadioButtonManual))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonGasolina)
                                    .addComponent(jRadioButtonDiesel)
                                    .addComponent(jRadioButtonHibrido)
                                    .addComponent(jRadioButtonElectrico)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGuardar)
                                .addGap(17, 17, 17))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMarca)
                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaMatriculacion)
                    .addComponent(jSpinnerFechaMatriculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKilometros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelColor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTransmision)
                    .addComponent(jLabelCombustible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonManual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAutomatica))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonGasolina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDiesel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonHibrido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonElectrico))
                    .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderColorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderColorStateChanged
        int color = jSliderColor.getValue();
        
        //Actualizo el color del fondo y de cada uno de los componentes.
        this.getContentPane().setBackground(new Color(color, color, color));
        for (Component component: this.getContentPane().getComponents()) {
            component.setForeground(new Color(255 -color, 255 -color, 255 -color));
        }
    }//GEN-LAST:event_jSliderColorStateChanged

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        //Miro si todos los atributos están establecidos, y si es así creo un nuevo coche que meto en la lista de coches.
        if (jComboBoxMarca.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una marca", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (buttonGroupTransmision.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una transmisión", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (buttonGroupCombustible.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar un combustible", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Coche.COCHES.add(new Coche(
                    jComboBoxMarca.getSelectedItem().toString(),
                    (int) jSpinnerFechaMatriculacion.getValue(),
                    jSliderKilometros.getValue(),
                    jSliderColor.getValue(),
                    buttonGroupTransmision.getSelection().getActionCommand(),
                    buttonGroupCombustible.getSelection().getActionCommand()
                ));
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jRadioButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoCoche dialog = new NuevoCoche(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCombustible;
    private javax.swing.ButtonGroup buttonGroupTransmision;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelCombustible;
    private javax.swing.JLabel jLabelFechaMatriculacion;
    private javax.swing.JLabel jLabelKilometros;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelTransmision;
    private javax.swing.JRadioButton jRadioButtonAutomatica;
    private javax.swing.JRadioButton jRadioButtonDiesel;
    private javax.swing.JRadioButton jRadioButtonElectrico;
    private javax.swing.JRadioButton jRadioButtonGasolina;
    private javax.swing.JRadioButton jRadioButtonHibrido;
    private javax.swing.JRadioButton jRadioButtonManual;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSlider jSliderColor;
    private javax.swing.JSlider jSliderKilometros;
    private javax.swing.JSpinner jSpinnerFechaMatriculacion;
    // End of variables declaration//GEN-END:variables
}
