package orm;
// Generated 20-ene-2025 23:56:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Libro generated by hbm2java
 */
@Entity
@Table(name="libro"
    ,catalog="DAM"
)
public class Libro  implements java.io.Serializable {


     private String nombre;
     private int edad;

    public Libro() {
    }

    public Libro(String nombre, int edad) {
       this.nombre = nombre;
       this.edad = edad;
    }
   
    @Id 
    @Column(name="nombre", unique=true, nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


