/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ord;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author PedroBorreganBurgos
 */
public class DialogoAlta extends javax.swing.JDialog {

    private Principal principal;
    
    /**
     * Creates new form DialogoAlta
     */
    public DialogoAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        principal = (Principal) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSituacion = new javax.swing.ButtonGroup();
        jSpinnerDonacion = new javax.swing.JSpinner();
        jComboBoxPago = new javax.swing.JComboBox<>();
        jButtonGrabar = new javax.swing.JButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jRadioButtonActivo = new javax.swing.JRadioButton();
        jRadioButtonParado = new javax.swing.JRadioButton();
        jLabelSituacion = new javax.swing.JLabel();
        jRadioButtonJubilado = new javax.swing.JRadioButton();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabelNick = new javax.swing.JLabel();
        jLabelClave = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelCP = new javax.swing.JLabel();
        jTextFieldNick = new javax.swing.JTextField();
        jTextFieldClave = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldCP = new javax.swing.JTextField();
        jCheckBoxNotificaciones = new javax.swing.JCheckBox();
        jLabelDonacion = new javax.swing.JLabel();
        jLabelPago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setIconImage(null);

        jSpinnerDonacion.setModel(new javax.swing.SpinnerNumberModel(10, 10, 200, 5));

        jComboBoxPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Trimestral", "Semestral", "Anual" }));
        jComboBoxPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPagoActionPerformed(evt);
            }
        });

        jButtonGrabar.setText("Grabar");
        jButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarActionPerformed(evt);
            }
        });

        buttonGroupSituacion.add(jRadioButtonActivo);
        jRadioButtonActivo.setText("Activo");

        buttonGroupSituacion.add(jRadioButtonParado);
        jRadioButtonParado.setText("Parado");
        jRadioButtonParado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonParadoActionPerformed(evt);
            }
        });

        jLabelSituacion.setText("Situación laboral");

        buttonGroupSituacion.add(jRadioButtonJubilado);
        jRadioButtonJubilado.setText("Jubilado");
        jRadioButtonJubilado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJubiladoActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(jRadioButtonActivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jRadioButtonParado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabelSituacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jRadioButtonJubilado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSituacion)
                    .addComponent(jRadioButtonActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonParado)
                    .addComponent(jRadioButtonJubilado))
                .addGap(6, 6, 6))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSituacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jRadioButtonParado)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonJubilado)
                .addGap(15, 15, 15))
        );

        jLayeredPane6.setBackground(new java.awt.Color(204, 204, 204));

        jLabelNick.setText("Nick");

        jLabelClave.setText("Clave");

        jLabelEmail.setText("E-mail");

        jLabelCP.setText("CP");

        jTextFieldNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNickActionPerformed(evt);
            }
        });

        jTextFieldClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClaveActionPerformed(evt);
            }
        });

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jTextFieldCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPActionPerformed(evt);
            }
        });

        jLayeredPane6.setLayer(jLabelNick, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabelClave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabelEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabelCP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jTextFieldNick, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jTextFieldClave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jTextFieldEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jTextFieldCP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNick)
                    .addComponent(jLabelClave)
                    .addComponent(jLabelEmail))
                .addGap(33, 33, 33)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNick, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jTextFieldClave)
                    .addComponent(jTextFieldEmail))
                .addGap(83, 83, 83)
                .addComponent(jLabelCP)
                .addGap(41, 41, 41)
                .addComponent(jTextFieldCP, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick)
                    .addComponent(jTextFieldNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClave)
                    .addComponent(jTextFieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCP))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jCheckBoxNotificaciones.setText("Recibir notificaciones");
        jCheckBoxNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNotificacionesActionPerformed(evt);
            }
        });

        jLabelDonacion.setText("Donacion");

        jLabelPago.setText("Tipo de pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDonacion)
                                    .addComponent(jLabelPago))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxPago, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(jSpinnerDonacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jCheckBoxNotificaciones)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDonacion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPago))
                        .addGap(26, 26, 26)
                        .addComponent(jCheckBoxNotificaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButtonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    private void jButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarActionPerformed
        
        //Extrae los resultados del formulario
        String nick = jTextFieldNick.getText();
        int clave = Integer.parseInt(jTextFieldClave.getText());
        String email = jTextFieldEmail.getText();
        int CP = Integer.parseInt(jTextFieldCP.getText());
        String situacion = buttonGroupSituacion.getSelection().toString();
        int donacion = (int) jSpinnerDonacion.getValue();
        String pago = (String) jComboBoxPago.getSelectedItem();
        String notificaciones = jCheckBoxNotificaciones.getActionCommand();
        
        //Validaciones
        if (!email.contains("@")){
            JOptionPane.showMessageDialog(this, "Introduce un e-mail válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (buttonGroupSituacion.getSelection() == null){
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una situación laboral.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            Afiliado.listaAfiliados.add(new Afiliado(nick, clave, email, CP, situacion, donacion, pago, notificaciones));   //Si todo está bien, añadimos
        }
        
        
        if (jComboBoxMarca.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una marca", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (buttonGroupTransmision.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una transmisión", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (buttonGroupCombustible.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar un combustible", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Coche.COCHES.add(new Coche(
                    jComboBoxMarca.getSelectedItem().toString(),
                    (int) jSpinnerFechaMatriculacion.getValue(),
                    jSliderKilometros.getValue(),
                    jSliderColor.getValue(),
                    buttonGroupTransmision.getSelection().getActionCommand(),
                    buttonGroupCombustible.getSelection().getActionCommand()
                ));
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonGrabarActionPerformed
    
    private void jComboBoxPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagoActionPerformed

    private void jRadioButtonParadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonParadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonParadoActionPerformed

    private void jRadioButtonJubiladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJubiladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonJubiladoActionPerformed

    private void jCheckBoxNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNotificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxNotificacionesActionPerformed

    private void jTextFieldNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNickActionPerformed

    }//GEN-LAST:event_jTextFieldNickActionPerformed

    private void jTextFieldClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClaveActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSituacion;
    private javax.swing.JButton jButtonGrabar;
    private javax.swing.JCheckBox jCheckBoxNotificaciones;
    private javax.swing.JComboBox<String> jComboBoxPago;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelDonacion;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelPago;
    private javax.swing.JLabel jLabelSituacion;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JRadioButton jRadioButtonActivo;
    private javax.swing.JRadioButton jRadioButtonJubilado;
    private javax.swing.JRadioButton jRadioButtonParado;
    private javax.swing.JSpinner jSpinnerDonacion;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldClave;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNick;
    // End of variables declaration//GEN-END:variables
}
