/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package exrec;

import exrec.logica.Viaje;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author IzanPerezDímas
 */
public class PantallaAlta extends javax.swing.JDialog {

    private boolean refresh = false;
    private float total = 0;
    
    /**
     * Creates new form NuevoCoche
     */
    public PantallaAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refresh = true;
        while (refresh == true){
            //if (tal esta marcado)...
                //total += ;
            //jLabelMensajeInterno.setText(total.toString());
        }
        
        //Establecer una imagen en una label
        final String RUTA_LOGO = "/src/imagenes/pokecoin.png";
        new ImageIcon(RUTA_LOGO).getImage().getScaledInstance(jLabelImg.getWidth(), jLabelImg.getHeight(), Image.SCALE_DEFAULT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTransmision = new javax.swing.ButtonGroup();
        buttonGroupCombustible = new javax.swing.ButtonGroup();
        jLabelMarca = new javax.swing.JLabel();
        jLabelFechaMatriculacion = new javax.swing.JLabel();
        jLabelKilometros = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jLabelTransmision = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jLabelCombustible = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jSpinnerFechaAlta = new javax.swing.JSpinner();
        jSpinnerFechaAlta1 = new javax.swing.JSpinner();
        jComboBoxProvincia = new javax.swing.JComboBox<>();
        jComboBoxProvincia1 = new javax.swing.JComboBox<>();
        jCheckBoxNegrita = new javax.swing.JCheckBox();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jCheckBoxNegrita1 = new javax.swing.JCheckBox();
        jCheckBoxCursiva = new javax.swing.JCheckBox();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jCheckBoxNegrita2 = new javax.swing.JCheckBox();
        jCheckBoxCursiva1 = new javax.swing.JCheckBox();
        jLabelMensajeInterno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerFechaMatriculacion = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang"); // NOI18N
        jLabelMarca.setText(bundle.getString("marca")); // NOI18N

        jLabelFechaMatriculacion.setText(bundle.getString("matriculacion")); // NOI18N

        jLabelKilometros.setText(bundle.getString("kilometros")); // NOI18N

        jLabelColor.setText(bundle.getString("color")); // NOI18N

        jLabelTransmision.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTransmision.setText(bundle.getString("tipoTransmision")); // NOI18N

        jSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelCombustible.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCombustible.setText(bundle.getString("tipoCombustible")); // NOI18N

        jButtonGuardar.setText(bundle.getString("guardar")); // NOI18N
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jSpinnerFechaAlta.setModel(new javax.swing.SpinnerDateModel());

        jSpinnerFechaAlta1.setModel(new javax.swing.SpinnerDateModel());

        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madrid", "Barcelona", "Sevilla" }));

        jComboBoxProvincia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madrid", "Barcelona", "Sevilla" }));
        jComboBoxProvincia1.setSelectedIndex(1);
        jComboBoxProvincia1.setSelectedItem(BARCELONA);

        jCheckBoxNegrita.setText("Ida y vuelta");

        jCheckBoxNegrita1.setText("Familia numerosa");
        jCheckBoxNegrita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNegrita1ActionPerformed(evt);
            }
        });

        jCheckBoxCursiva.setText("Jubilado");

        jLayeredPane3.setLayer(jCheckBoxNegrita1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jCheckBoxCursiva, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxNegrita1)
                    .addComponent(jCheckBoxCursiva))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxNegrita1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxCursiva)
                .addGap(32, 32, 32))
        );

        jCheckBoxNegrita2.setText("Maleta adicional");
        jCheckBoxNegrita2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNegrita2ActionPerformed(evt);
            }
        });

        jCheckBoxCursiva1.setText("Selección de asiento");

        jLayeredPane4.setLayer(jCheckBoxNegrita2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jCheckBoxCursiva1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxNegrita2)
                    .addComponent(jCheckBoxCursiva1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxNegrita2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxCursiva1)
                .addGap(32, 32, 32))
        );

        jLabelMensajeInterno.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setText("Precio total:");

        jSpinnerFechaMatriculacion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));

        jLabel2.setText("Nº viajeros:");

        jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pokecoin.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelTransmision)
                                .addGap(101, 101, 101)
                                .addComponent(jLabelCombustible))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMensajeInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaMatriculacion)
                            .addComponent(jLabelKilometros)
                            .addComponent(jLabelColor)
                            .addComponent(jLabelMarca)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerFechaAlta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinnerFechaAlta1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxProvincia1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerFechaMatriculacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxNegrita)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMarca)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabelFechaMatriculacion)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabelKilometros))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(jLabelColor)))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxProvincia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnerFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxNegrita))
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerFechaAlta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerFechaMatriculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTransmision)
                                    .addComponent(jLabelCombustible))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10))
                            .addComponent(jLabelMensajeInterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jButtonGuardar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        //Miro si todos los atributos están establecidos, y si es así creo un nuevo coche que meto en la lista de coches.
        if (jComboBoxMarca.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una marca", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (buttonGroupTransmision.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una transmisión", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (buttonGroupCombustible.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar un combustible", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Viaje.COCHES.add(new Viaje(
                    jComboBoxMarca.getSelectedItem().toString(),
                    (int) jSpinnerFechaMatriculacion.getValue(),
                    jSliderKilometros.getValue(),
                    jSliderColor.getValue(),
                    buttonGroupTransmision.getSelection().getActionCommand(),
                    buttonGroupCombustible.getSelection().getActionCommand()
                ));
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jCheckBoxNegrita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNegrita1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxNegrita1ActionPerformed

    private void jCheckBoxNegrita2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNegrita2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxNegrita2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaAlta dialog = new PantallaAlta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCombustible;
    private javax.swing.ButtonGroup buttonGroupTransmision;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JCheckBox jCheckBoxCursiva;
    private javax.swing.JCheckBox jCheckBoxCursiva1;
    private javax.swing.JCheckBox jCheckBoxNegrita;
    private javax.swing.JCheckBox jCheckBoxNegrita1;
    private javax.swing.JCheckBox jCheckBoxNegrita2;
    private javax.swing.JComboBox<String> jComboBoxProvincia;
    private javax.swing.JComboBox<String> jComboBoxProvincia1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelCombustible;
    private javax.swing.JLabel jLabelFechaMatriculacion;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelKilometros;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMensajeInterno;
    private javax.swing.JLabel jLabelTransmision;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSpinner jSpinnerFechaAlta;
    private javax.swing.JSpinner jSpinnerFechaAlta1;
    private javax.swing.JSpinner jSpinnerFechaMatriculacion;
    // End of variables declaration//GEN-END:variables
}
