package orm;
// Generated 19-feb-2025 10:36:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name="formaPago"
    ,catalog="gimnasioExamen4"
)
public class FormaPago  implements java.io.Serializable {


     private Integer codPago;
     private String nomPago;
     private Set socioses = new HashSet(0);

    public FormaPago() {
    }

	
    public FormaPago(String nomPago) {
        this.nomPago = nomPago;
    }
    public FormaPago(String nomPago, Set socioses) {
       this.nomPago = nomPago;
       this.socioses = socioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cod_pago", unique=true, nullable=false)
    public Integer getCodPago() {
        return this.codPago;
    }
    
    public void setCodPago(Integer codPago) {
        this.codPago = codPago;
    }

    
    @Column(name="nom_pago", nullable=false, length=10)
    public String getNomPago() {
        return this.nomPago;
    }
    
    public void setNomPago(String nomPago) {
        this.nomPago = nomPago;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaPago")
    public Set getSocioses() {
        return this.socioses;
    }
    
    public void setSocioses(Set socioses) {
        this.socioses = socioses;
    }

    @Override
    public String toString() {
        return "pago= " + nomPago;
    }

    public String toStringSelectForm(){
        return "codPago=" + codPago + "\t\t\tnomPago= " + nomPago;
    }
}


