package orm;
// Generated 19-feb-2025 10:36:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Planes generated by hbm2java
 */
@Entity
@Table(name="planes"
    ,catalog="gimnasioExamen4"
)
public class Planes  implements java.io.Serializable {


     private Integer codPlan;
     private String nomPlan;
     private float cuotaPlan;
     private Set socioses = new HashSet(0);

    public Planes() {
    }

	
    public Planes(String nomPlan, float cuotaPlan) {
        this.nomPlan = nomPlan;
        this.cuotaPlan = cuotaPlan;
    }
    public Planes(String nomPlan, float cuotaPlan, Set socioses) {
       this.nomPlan = nomPlan;
       this.cuotaPlan = cuotaPlan;
       this.socioses = socioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cod_plan", unique=true, nullable=false)
    public Integer getCodPlan() {
        return this.codPlan;
    }
    
    public void setCodPlan(Integer codPlan) {
        this.codPlan = codPlan;
    }

    
    @Column(name="nom_plan", nullable=false, length=10)
    public String getNomPlan() {
        return this.nomPlan;
    }
    
    public void setNomPlan(String nomPlan) {
        this.nomPlan = nomPlan;
    }

    
    @Column(name="cuota_plan", nullable=false, precision=12, scale=0)
    public float getCuotaPlan() {
        return this.cuotaPlan;
    }
    
    public void setCuotaPlan(float cuotaPlan) {
        this.cuotaPlan = cuotaPlan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planes")
    public Set getSocioses() {
        return this.socioses;
    }
    
    public void setSocioses(Set socioses) {
        this.socioses = socioses;
    }

    @Override
    public String toString() {
        return "plan=" + nomPlan;
    }


    public String toStringSelectForm(){
        return "codPlan=" + codPlan + "\t\t\tnomPlan= " + nomPlan + "\t\t\tcuotaPlan= " + cuotaPlan;
    }
}


