package orm;
// Generated 19-feb-2025 10:36:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Socios generated by hbm2java
 */
@Entity
@Table(name="socios"
    ,catalog="gimnasioExamen4"
)
public class Socios  implements java.io.Serializable {


     private Integer idSocio;
     private FormaPago formaPago;
     private Planes planes;
     private String apeSocio;
     private float cuotaCli;

    public Socios() {
    }

    public Socios(FormaPago formaPago, Planes planes, String apeSocio, float cuotaCli) {
       this.formaPago = formaPago;
       this.planes = planes;
       this.apeSocio = apeSocio;
       this.cuotaCli = cuotaCli;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_socio", unique=true, nullable=false)
    public Integer getIdSocio() {
        return this.idSocio;
    }
    
    public void setIdSocio(Integer idSocio) {
        this.idSocio = idSocio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pago", nullable=false)
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_plan", nullable=false)
    public Planes getPlanes() {
        return this.planes;
    }
    
    public void setPlanes(Planes planes) {
        this.planes = planes;
    }

    
    @Column(name="ape_socio", nullable=false, length=15)
    public String getApeSocio() {
        return this.apeSocio;
    }
    
    public void setApeSocio(String apeSocio) {
        this.apeSocio = apeSocio;
    }

    
    @Column(name="cuota_cli", nullable=false, precision=12, scale=0)
    public float getCuotaCli() {
        return this.cuotaCli;
    }
    
    public void setCuotaCli(float cuotaCli) {
        this.cuotaCli = cuotaCli;
    }

    @Override
    public String toString() {
        return "idSocio=" + idSocio + "\t\tape=" + apeSocio+ "\t\tcuotaCli=" + cuotaCli + "\t\t" + formaPago + "\t\t" + planes;
    }




}


