package orm;
// Generated 10-feb-2025 18:08:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tareas generated by hbm2java
 */
@Entity
@Table(name="tareas"
    ,catalog="ad_ut3_ej1"
)
public class Tareas  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private boolean finalizada;

    public Tareas() {
    }

	
    public Tareas(Date fechaInicio, boolean finalizada) {
        this.fechaInicio = fechaInicio;
        this.finalizada = finalizada;
    }
    public Tareas(String descripcion, Date fechaInicio, Date fechaFin, boolean finalizada) {
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.finalizada = finalizada;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=7)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="finalizada", nullable=false)
    public boolean isFinalizada() {
        return this.finalizada;
    }
    
    public void setFinalizada(boolean finalizada) {
        this.finalizada = finalizada;
    }

    @Override
    public String toString() {
        return "Tareas{" + "id=" + id + ", descripcion=" + descripcion + ", fechaInicio=" + fechaInicio + ", fechaFin=" + fechaFin + ", finalizada=" + finalizada + '}';
    }
}


