package orm;
// Generated 10-feb-2025 18:08:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TareasValues generated by hbm2java
 */
@Entity
@Table(name="tareasValues"
    ,catalog="ad_ut3_ej1"
)
public class TareasValues  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private boolean finalizada;

    public TareasValues() {
    }

	
    public TareasValues(int id, String descripcion, Date fechaInicio, boolean finalizada) {
        this.id = id;
        this.descripcion = descripcion;
        this.fechaInicio = fechaInicio;
        this.finalizada = finalizada;
    }
    public TareasValues(int id, String descripcion, Date fechaInicio, Date fechaFin, boolean finalizada) {
       this.id = id;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.finalizada = finalizada;
    }
   
    @Id 
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", nullable=false, length=6)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="finalizada", nullable=false)
    public boolean isFinalizada() {
        return this.finalizada;
    }
    
    public void setFinalizada(boolean finalizada) {
        this.finalizada = finalizada;
    }




}


